using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Neruna.Core;
using Neruna.Core.Accounts;
using Neruna.Core.Calendar;
using Neruna.Core.Contacts;
using Neruna.Core.Providers;
using static Neruna.Core.Localization.Texts;

namespace Neruna.Providers.Special;

/// <summary>When a birthday reminds: not, on the day, the day before or a week before (each at 9:00).</summary>
public enum BirthdayReminder
{
    None,
    OnTheDay,
    DayBefore,
    WeekBefore,
}

/// <summary>
/// Read-only calendars Neruna computes itself, without a server: the events of a few years around today, rebuilt on
/// every sync (the sync state is the content hash, so nothing changes in storage while the result is the same).
/// </summary>
public abstract class GeneratedCalendarProvider(Guid connectionId, TimeProvider time) : ICalendarProvider
{
    // Last year (for looking back) up to two years ahead.
    private const int YearsBack = 1;
    private const int YearsAhead = 2;

    public CalendarProviderCapabilities Capabilities => CalendarProviderCapabilities.None;

    protected abstract string RemoteId { get; }

    protected abstract string Name { get; }

    protected abstract string Color { get; }

    public virtual Task TestConnectionAsync(CancellationToken cancellationToken = default) => Task.CompletedTask;

    public Task<IReadOnlyList<CalendarInfo>> GetCalendarsAsync(CancellationToken cancellationToken = default) =>
        Task.FromResult<IReadOnlyList<CalendarInfo>>([new CalendarInfo(connectionId, RemoteId, Name, Color, IsReadOnly: true)]);

    public async Task<CalendarSyncResult> SyncCalendarAsync(CalendarInfo calendar, IReadOnlyDictionary<string, string?> knownVersions, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(calendar);
        var year = time.GetLocalNow().Year;
        var items = (await GenerateAsync(year - YearsBack, year + YearsAhead, cancellationToken)).OrderBy(i => i.RemoteId, StringComparer.Ordinal).ToList();
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(string.Join('\n', items.Select(i => i.ICalendarData)))));
        return hash == calendar.SyncState
            ? new CalendarSyncResult(hash, IsFullResync: false, [], [])
            : new CalendarSyncResult(hash, IsFullResync: true, items, []);
    }

    public Task<CalendarObject> SaveAsync(CalendarInfo calendar, CalendarObject item, CancellationToken cancellationToken = default) =>
        throw new NotSupportedException("This calendar is generated by Neruna and read-only.");

    public Task DeleteAsync(CalendarInfo calendar, CalendarObject item, CancellationToken cancellationToken = default) =>
        throw new NotSupportedException("This calendar is generated by Neruna and read-only.");

    public ValueTask DisposeAsync()
    {
        GC.SuppressFinalize(this);
        return ValueTask.CompletedTask;
    }

    protected abstract Task<IReadOnlyList<CalendarObject>> GenerateAsync(int fromYear, int toYear, CancellationToken cancellationToken);

    /// <summary>An all-day, free (TRANSP:TRANSPARENT) event; <paramref name="alarm"/> e.g. "-PT15H" relative to its start.</summary>
    protected static CalendarObject AllDay(string uid, DateOnly date, string summary, string? description, string category, string? alarm)
    {
        var text = new StringBuilder()
            .Append("BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Neruna//Neruna Desktop//DE\r\nBEGIN:VEVENT\r\n")
            .Append(CultureInfo.InvariantCulture, $"UID:{uid}\r\n")
            .Append("DTSTAMP:20000101T000000Z\r\n") // fixed, so the content hash only changes with the content
            .Append(CultureInfo.InvariantCulture, $"DTSTART;VALUE=DATE:{date:yyyyMMdd}\r\n")
            .Append(CultureInfo.InvariantCulture, $"DTEND;VALUE=DATE:{date.AddDays(1):yyyyMMdd}\r\n")
            .Append(CultureInfo.InvariantCulture, $"SUMMARY:{Escape(summary)}\r\n")
            .Append(CultureInfo.InvariantCulture, $"CATEGORIES:{category}\r\n")
            .Append("TRANSP:TRANSPARENT\r\n");
        if (description is not null)
        {
            text.Append(CultureInfo.InvariantCulture, $"DESCRIPTION:{Escape(description)}\r\n");
        }

        if (alarm is not null)
        {
            text.Append(CultureInfo.InvariantCulture, $"BEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:{Escape(summary)}\r\nTRIGGER:{alarm}\r\nEND:VALARM\r\n");
        }

        text.Append("END:VEVENT\r\nEND:VCALENDAR\r\n");
        return new CalendarObject(uid, ETag: null, text.ToString());
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace(";", "\\;", StringComparison.Ordinal)
            .Replace(",", "\\,", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal).Replace("\r", string.Empty, StringComparison.Ordinal);
}

/// <summary>The birthdays of all contacts (vCard BDAY) in all address books, with the age when the year is known.</summary>
public sealed class BirthdayCalendarProvider(Guid connectionId, IContactStore contacts, BirthdayReminder reminder, TimeProvider time)
    : GeneratedCalendarProvider(connectionId, time)
{
    public const string ReminderSetting = "reminder";

    protected override string RemoteId => "birthdays";

    protected override string Name => T("Geburtstage");

    protected override string Color => "#C239B3";

    public static string Format(BirthdayReminder reminder) => reminder switch
    {
        BirthdayReminder.OnTheDay => "day",
        BirthdayReminder.DayBefore => "daybefore",
        BirthdayReminder.WeekBefore => "week",
        _ => "none",
    };

    public static BirthdayReminder ParseReminder(string? value) => value switch
    {
        "day" => BirthdayReminder.OnTheDay,
        "daybefore" => BirthdayReminder.DayBefore,
        "week" => BirthdayReminder.WeekBefore,
        _ => BirthdayReminder.None,
    };

    protected override async Task<IReadOnlyList<CalendarObject>> GenerateAsync(int fromYear, int toYear, CancellationToken cancellationToken)
    {
        var alarm = reminder switch
        {
            BirthdayReminder.OnTheDay => "PT9H",
            BirthdayReminder.DayBefore => "-PT15H",
            BirthdayReminder.WeekBefore => "-P6DT15H",
            _ => null,
        };
        var result = new List<CalendarObject>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var book in await contacts.GetAddressBooksAsync(null, cancellationToken))
        {
            foreach (var contact in await contacts.GetContactsAsync(book.ConnectionId, book.RemoteId, cancellationToken))
            {
                var card = VCardReader.Read(contact.VCardData);
                if (card.Birthday is not { } birthday || card.IsGroup)
                {
                    continue;
                }

                // The same person in two address books: once.
                var key = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{card.DisplayName}|{birthday}")))[..16];
                if (!seen.Add(key))
                {
                    continue;
                }

                for (var year = fromYear; year <= toYear; year++)
                {
                    if (birthday.Year is { } born && year < born)
                    {
                        continue;
                    }

                    var summary = birthday.Year is { } y && year > y
                        ? F("Geburtstag: {0} ({1})", card.DisplayName, year - y)
                        : F("Geburtstag: {0}", card.DisplayName);
                    result.Add(AllDay($"neruna-birthday-{key}-{year}", birthday.In(year), summary, null, "BIRTHDAY", alarm));
                }
            }
        }

        return result;
    }
}

/// <summary>Public holidays of one country and region (see <see cref="Holidays"/>).</summary>
public sealed class HolidayCalendarProvider(Guid connectionId, string country, string? region, TimeProvider time)
    : GeneratedCalendarProvider(connectionId, time)
{
    public const string CountrySetting = "country";
    public const string RegionSetting = "region";

    protected override string RemoteId => region is null ? $"holidays-{country}" : $"holidays-{country}-{region}";

    protected override string Name => F("Feiertage {0}", Holidays.DisplayName(country, region));

    protected override string Color => "#0B8A3E";

    public override Task TestConnectionAsync(CancellationToken cancellationToken = default)
    {
        _ = Holidays.For(country, region, 2000); // unknown country or region: fails here, before the calendar is added
        return Task.CompletedTask;
    }

    protected override Task<IReadOnlyList<CalendarObject>> GenerateAsync(int fromYear, int toYear, CancellationToken cancellationToken)
    {
        var result = new List<CalendarObject>();
        for (var year = fromYear; year <= toYear; year++)
        {
            foreach (var holiday in Holidays.For(country, region, year))
            {
                result.Add(AllDay($"neruna-{RemoteId}-{holiday.Date:yyyyMMdd}-{result.Count}", holiday.Date, holiday.Name,
                    holiday.DayOff ? null : T("Meist kein arbeitsfreier Tag."), "HOLIDAY", alarm: null));
            }
        }

        return Task.FromResult<IReadOnlyList<CalendarObject>>(result);
    }
}

public sealed class BirthdayProviderFactory(IContactStore contacts, TimeProvider time) : IProviderFactory<ICalendarProvider>
{
    public string ProviderId => ProviderIds.Birthdays;

    public string DisplayName => T("Geburtstage");

    public ICalendarProvider Create(ServiceConnection connection)
    {
        ArgumentNullException.ThrowIfNull(connection);
        return new BirthdayCalendarProvider(connection.Id, contacts,
            BirthdayCalendarProvider.ParseReminder(connection.Settings.GetValueOrDefault(BirthdayCalendarProvider.ReminderSetting)), time);
    }
}

public sealed class HolidayProviderFactory(TimeProvider time) : IProviderFactory<ICalendarProvider>
{
    public string ProviderId => ProviderIds.Holidays;

    public string DisplayName => T("Feiertage");

    public ICalendarProvider Create(ServiceConnection connection)
    {
        ArgumentNullException.ThrowIfNull(connection);
        var country = connection.Settings.GetValueOrDefault(HolidayCalendarProvider.CountrySetting)
                      ?? throw new InvalidOperationException("Holiday calendar without country.");
        return new HolidayCalendarProvider(connection.Id, country, connection.Settings.GetValueOrDefault(HolidayCalendarProvider.RegionSetting), time);
    }
}
